# Installing Pytorch & Importing 

In [2]:
#Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3 MB 3.3 kB/s  eta 0:00:01    |██████████▊                     | 53.5 MB 22.4 MB/s eta 0:00:05     |██████████████▏                 | 70.4 MB 26.4 MB/s eta 0:00:04
     |████████████████████████████████| 11.8 MB 31.9 MB/s eta 0:00:01
     |████████████████████████████████| 7.6 MB 13.3 MB/s eta 0:00:01
  Attempting uninstall: torch
    Found existing installation: torch 1.7.0
    Uninstalling torch-1.7.0:
      Successfully uninstalled torch-1.7.0
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.8.1
    Uninstalling torchvision-0.8.1:
      Successfully uninstalled torchvision-0.8.1
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 0.7.0a0+ac17b64
    Uninstalling torchaudio-0.7.0a0+ac17b64:
      Successfully uninstalled torchaudio-0.7.0a0+ac17b64


In [3]:
import torch

# About Tensors

*We would be learning about Tensors. Tensors can be a number, a metrix, a vector or a 3D array. In the follwoing example, using ```'.'``` indicates the data type to be a float.*

In [4]:
# Creating our first variable T1. 
T1 = torch.tensor(3.)
T1

tensor(3.)

In [5]:
# For more complex examples, Lets try creating a vector Tensor
T2 = torch.tensor([2, 1., 4, 6, 5.])
print('Vector Tensor:  \n' , T2)

Vector Tensor:  
 tensor([2., 1., 4., 6., 5.])


In [6]:
# For more complex examples, Lets try creating a matrix Tensor

T3 = torch.tensor([[2, 1.], 
                  [5, 7.], 
                  [10., 5 ]])
print('Matrix Tensor:  \n' , T3)

Matrix Tensor:  
 tensor([[ 2.,  1.],
        [ 5.,  7.],
        [10.,  5.]])


In [7]:
# For more complex examples, Lets try creating a 3-D Array Tensor

T4 = torch.tensor([[[2, 1. , 4], 
                  [5, 7., 9]], 
                  [[10., 5 ,16] ,
                  [33, 56. , 66]]])
print('3-D Array:  \n' , T4)

3-D Array:  
 tensor([[[ 2.,  1.,  4.],
         [ 5.,  7.,  9.]],

        [[10.,  5., 16.],
         [33., 56., 66.]]])


# Tensor Functions

*The Torch module also contains many functions for creating and manipulating tensors. *

* *Creating a matrix of a size *3x2* *having a fixed value.*
* **Cat** *function joins the two tensors. Make sure the tensors you want to join should be of the same size.*
* *Using functions like ```tan, cos, sin```*
* *Changing the shape of an existing tensor / concatenated tensor.*

In [8]:
T5 = torch.full((3,2), 42) #Using full fucntion to create a new tenor 
print('New Tensor T5:  \n' , T5) # Printing the value 


New Tensor T5:  
 tensor([[42, 42],
        [42, 42],
        [42, 42]])


In [9]:
# Joining two tenors with same dimmensions by using CAT fucntion
T6 = torch.cat((T3, T5))
print('T6:  \n' , T6) # Printing the value 

T6:  
 tensor([[ 2.,  1.],
        [ 5.,  7.],
        [10.,  5.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])


In [10]:
# Using mathematical functions like tan, sin, cos

T7 = torch.sin(T6)
print('T7:  \n' , T7) # Printing the value 

T7:  
 tensor([[ 0.9093,  0.8415],
        [-0.9589,  0.6570],
        [-0.5440, -0.9589],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])


In [12]:
# Change the shape of a tensor
T8 = T7.reshape((3,2,2))
print('T8:  \n' , T8) # Printing the value 

T8:  
 tensor([[[ 0.9093,  0.8415],
         [-0.9589,  0.6570]],

        [[-0.5440, -0.9589],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])


# Using Numpy & Pandas

* *Converting a numpy array to a  torch tensor using* ```torch.from_numpy```

* *Converting a tensor to numpy array using* ``` .numpy() ```

In [18]:
import numpy as np 

x = np.array([[2,4.5],[5,3],[7.2,1],[9,10]]) #Creating a numpy Array
print('This is a numpy array: \n' , x) 

tensor_arr = torch.from_numpy(x) # Converting the numpy array to tensor
print('Tensor Array:  \n' , tensor_arr)

#Checking the type of both the arrays
ty_x = x.dtype
ty_y = tensor_arr.dtype

print(ty_x,ty_y)


This is a numpy array: 
 [[ 2.   4.5]
 [ 5.   3. ]
 [ 7.2  1. ]
 [ 9.  10. ]]
Tensor Array:  
 tensor([[ 2.0000,  4.5000],
        [ 5.0000,  3.0000],
        [ 7.2000,  1.0000],
        [ 9.0000, 10.0000]], dtype=torch.float64)
float64 torch.float64
This is the converted numpy array:  
 [[ 2.   4.5]
 [ 5.   3. ]
 [ 7.2  1. ]
 [ 9.  10. ]]


In [19]:
#Converting tensor to numpy 
num_arr = tensor_arr.numpy()
print('This is the converted numpy array:  \n' , num_arr)

This is the converted numpy array:  
 [[ 2.   4.5]
 [ 5.   3. ]
 [ 7.2  1. ]
 [ 9.  10. ]]


*Interoperability between PyTorch and Numpy is essential.* 

**WHY ?**

*Because the data reading and processing would be mostly done with the help of numpy.*

**Then why PyTorch at all ??**
* **Autograd**
The ability to ```automatically``` computing the ```gradients``` for tensor operation which is quite essential for deep learning models. 

* **GPU** 
As we would be working with a large dataset, operations can be perfomaed efficiently using GPU.  

# Saving & Uploading 


In [20]:
#This is a temporary step. 
#!pip install jovian --upgrade --quiet
#import jovian
#jovian.commit(project='01-pytorch-basics')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Detected Kaggle notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Uploading notebook to https://jovian.ai/neickz02/01-pytorch-basics


<IPython.core.display.Javascript object>